### ISSUE TITLE
CrystalDebris lag the game out to a halt when embedded in moving objects

### ISSUE THREAD

**Issue by GreyMario** [EverestAPI/Everest#132]
This makes installing a Crystal Shatter trigger anywhere near a Floaty Space Block, Intro Crusher, Zip Mover, Swap Block, or Star Jump Block a recipe for disaster.

**Comment by max4805** [comment]
Investigation ongoing. Looks like those debris are approaching light speed though.

![image](https://user-images.githubusercontent.com/52103563/79071835-124f6b00-7cde-11ea-9103-585c2fa1f865.png)

**Comment by max4805** [comment]
Okay, looks like that on collision, Y speed gets multiplied by -1.2. This _doesn't end up well_ if the debris get stuck in something, and as such, collides repeatedly with it. Since the debris are moved pixel per pixel to check for collisions on the way, moving something by 4.5 million pixels takes quite a bit of time. 🤔
