### ISSUE TITLE
Option to quit (not restart) Celeste after updating mods [enhancement]

### ISSUE THREAD

**Issue by ZacharyTalis** [EverestAPI/Everest#249]
**Current behavior:** Once mod updates are downloaded from the menu, "press [keybind] to restart Celeste" is the only way to exit this menu.

**Proposed behavior:** Keep this option and add a new option, "press [keybind] to quit Celeste", which closes the game without a restart.

**Explanation for proposal:** Oftentimes, updating mods is the last thing I do before exiting Celeste for the day. If possible, not having to launch the game again would be phenomenal ❤

**Possible issue:** Restarting Celeste might facilitate mod installation? I'm not sure.

**Comment by maddie480** [comment]
Restarting or closing would make no difference when it comes to updating (what matters is that you don't continue using the game without a restart). 😅

Though I'm not sure which button binding you would press to quit instead of restarting 🤔 there aren't that many used in menus (I can think of confirm, back and journal).

**Comment by ZacharyTalis** [comment]
@max4805 any binding should work! Though I believe the current binding for restart is `back`, so probably not that one.

**Comment by WEGFan** [comment]
🤔 actually pressing Quick Restart for restart and Back for quit may be better, but since Back is used for restart for a long time now, changing the binding may cause some people confused. I can't think of a better key for quit, maybe Journal?
