### ISSUE TITLE
Adware/malware warning in ClamAV

### ISSUE THREAD

**Issue by i-can-not-program** [EverestAPI/Everest#260]
![Screenshot from 2020-12-14 21-50-25](https://user-images.githubusercontent.com/67367193/102061253-17118380-3e58-11eb-9851-cf03ba6cb707.png)
I thought it was worth reporting that ClamAV detected Malware in discord-rpc.dll.

Everest Version: Latest stable version as of 4:07 am Monday, 14 December 2020 (GMT-5)

**Comment by 0x0ade** [comment]
This is a false positive. discord-rpc.dll was taken from [the official Discord RPC repository](https://github.com/discord/discord-rpc/releases) and hasn't been modified in any way or even updated for a very long time now. Antivirus software likes to go ham on anything that either modifies other .exes (Everest installer / Everest itself) or anything communicating with outside applications (Discord RPC) because "it could be a virus - maybe isn't but it could be."
