### ISSUE TITLE
Replace DiscordRPC with GameSDK

### ISSUE THREAD

**Issue by coloursofnoise** [EverestAPI/Everest#307]
The [Everest DiscordRPC](https://github.com/EverestAPI/Everest/blob/0d098aab868084d5b5fc649fd15a35edd6e21557/Celeste.Mod.mm/Mod/Everest/Everest.Discord.cs) integration is broken on MacOS, and the [DiscordRPC Library](https://github.com/discord/discord-rpc) has been deprecated in favour of [Discord's GameSDK](https://discord.com/developers/docs/game-sdk/sdk-starter-guide).

**Comment by endorpersand** [comment]
I believe I have figured out why Everest's DiscordRPC integration is broken on macOS.

In the current Everest code, the platform is being checked like so:
```cs
if (!string.IsNullOrEmpty(CoreModule.Settings.DiscordLib))
    lib = CoreModule.Settings.DiscordLib;
else if (Environment.OSVersion.Platform == PlatformID.Win32NT)
    lib = "discord-rpc.dll";
else if (Environment.OSVersion.Platform == PlatformID.MacOSX) {
    lib = "libdiscord-rpc.dylib";
    // FIXME: macOS doesn't see libdiscord-rpc.dylib wherever Celeste.exe is.
} else if (Environment.OSVersion.Platform == PlatformID.Unix)
    lib = "libdiscord-rpc.so";
```

However, on macOS, `Environment.OSVersion.Platform` is `Unix`, not `MacOSX`. So, Everest tries to use `libdiscord-rpc.so` rather than `libdiscord-rpc.dylib`, causing rich presence to fail on macOS.

At the moment, a workaround for current macOS users is to open `Saves > modsettings-Everest.celeste` and replace the line `DiscordLib: ''` with `DiscordLib: libdiscord-rpc.dylib`.

A possible permanent solution would be to try `libdiscord-rpc.so` on Unix platforms and then try `libdiscord-rpc.dylib` if `libdiscord-rpc.so` fails.

**Comment by KTibow** [comment]
reposting this since someone from the discord recommended me to
it would be nice if when you folks get around to replacing the discord rich presence component, you could also improve the design a bit, in a couple ways
1. remove the original rich presence (if possible); having 2 rich presences are bad
2. use the image; it makes things feel more aligned, gives an opportunity to add art, and lets you add another text field (see https://discord.com/developers/docs/rich-presence/best-practices#use-all-of-the-fields-where-applicable)
3. consider using words instead of emoji, it makes it more understandable
4. consider moving around things to match up with the field names; see the page i linked before, also [this diagram](https://discord.com/assets/43bef54c8aee2bc0fd1c717d5f8ae28a.png)

**Comment by Kalobi** [comment]
@KTibow What would you suggest using for the image? The current map icon?

**Comment by KTibow** [comment]
I'm not sure. Could you give some examples of the icons?

**Comment by Kalobi** [comment]
@KTibow This would be the icon for Resort, for example:
![resort](https://user-images.githubusercontent.com/46748261/195894659-627682cb-ec5d-4507-ad42-5e9655a173b0.png)

**Comment by maddie480** [comment]
I'm not sure how that'd work with arbitrary images 🤔 

![image](https://user-images.githubusercontent.com/52103563/196007157-c9a09b44-0cdb-4b75-8f69-69080eee61da.png)

**Comment by max4805** [comment]
You can make their "media proxy" proxy anything (like, https://media.discordapp.net/external/QtIxTXtNkB4eSkFOQBmaXZ3yZCA9JiuMBWFI1OZ5OHE/https/celestemodupdater.0x0a.de/banana-mirror-images/img_ss_mods_5f53e04d0cf8f.png) but I'm not really sure how you come up with that link, besides literally posting the link on Discord and reading the message back

**Comment by maddie480** [comment]
From what I understand, you send an image URL, Discord proxies it, and if you read back your presence you get mp:{some_proxy_url} (for example https://media.discordapp.net/external/QtIxTXtNkB4eSkFOQBmaXZ3yZCA9JiuMBWFI1OZ5OHE/https/celestemodupdater.0x0a.de/banana-mirror-images/img_ss_mods_5f53e04d0cf8f.png), so that would probably require mirroring map icons 🤔

**Comment by maddie480** [comment]
Started working on it 😄
