### ISSUE TITLE
Crash reports always say out of memory error and it's really not helpful

### ISSUE THREAD

**Issue by Traehgniw** [EverestAPI/Everest#39]
Steps to reproduce: Be on the latest version (and possibly other newish versions but eh).
Download the mario bros 1-1 level map. 
Complete it. 
The error message is supposed to be this : https://gist.github.com/Hugman76/c03083743268ebaaf4450c9628fd599a
(a null reference error)
but instead it's an out of memory error

this bug report brought to you by "okay, _something_ failed to download properly and is crashing everest on startup, but installer_log.txt isn't helping and the crash text is lies"

**Comment by 0x0ade** [comment]
There is not supposed to be an error at all.

The error you linked is because whoever uploaded that log is using an outdated - possibly pirated - version of Celeste.

I can't help you with your issue without _your_ error_log.txt. The installer log is for the Everest installer itself, and I guess the game crashes on startup for you.

Enable dynamic texture loading in the mod options, then go to the main menu and exit the game from there. If that still doesn't work, either your GPU is too old to play Celeste with that mod, or you have too little RAM installed.

Please go to the Discord server for any further help.

**Comment by Traehgniw** [comment]
The super mario bros thing was crashing for me too. I restarted my computer and now everything works, but what this error is about is that _every Everest error I got in my error log was "out of memory error"_. 
And I had task manager open. It never went above 12% GPU useage and had five gigabytes of RAM available. 
I had gotten an error about a corrupted file download when trying to install mods that told me to look at installer_log.txt, so I did-both of them. One of them was about installing Everest, one was about successfully downloading the halloween collab. 
Here's my error log, never been cleared. There's a whole chunk of those that are actually from forgetting to install a dependecy for a mod and Everest freaking out about it (installing the dependency fixed it), but they ALL say they're out-of-memory errors.

[error_log.txt](https://github.com/EverestAPI/Everest/files/3076954/error_log.txt)

**Comment by 0x0ade** [comment]
Those OutOfMemoryExceptions were caused by an audio bank inside one of the mods you had installed and by the game running out of VRAM. The game is a 32-bit process, meaning that it won't be able to make use of all of your 5 GB of RAM, and GPU usage doesn't always match GPU VRAM usage.

Glad to hear that it works now though :)
