### ISSUE TITLE
Add vanilla debug console bind back

### ISSUE THREAD

**Issue by LozenChen** [EverestAPI/Everest#679]
### I am planning on implementing this myself

No

### Describe your request

https://github.com/EverestAPI/Everest/commit/52fe16530bca6c3a2e5b0bbf69139da8caea0ea5#diff-cf4a535cfc29da44fe0473fa6a78de4004c50841cc42c2ec3b16da674103f64aL369

I don't see why this bind should be removed
but at least Everest should provide a configurable button binding to close debug console, instead of can only using ESC or the Q command
otherwise it would be inconvenient for people that get used to the button '`'

**Comment by Kalobi** [comment]
The issue is that we can't detect *buttons* while the console is open, only *characters*. Having hardcoded characters that automatically close the console is an issue. For example, these characters are perfectly legal in room names, so it prevents you from using the `load` command to teleport to a room that contains ~ in its name. And making it customizable sucks because it uses characters, not keys. We can't reliably convert keys bound in a keyboard config menu to characters, so we'd have to add something like a text input setting that lets you enter a character to close the console, which is just incredibly jank.

**Comment by microlith57** [comment]
why can't we detect buttons with the console open?

**Comment by Kalobi** [comment]
Because `MInput.Update` specifically calls `Keyboard.UpdateNull` instead of `Keyboard.Update` while the console is open to prevent typing in the console also triggering gameplay actions. I guess technically we could manually bypass the keyboard part of input handling, get the keyboard state directly, and reimplement half of the input stack for a single case.

**Comment by Kalobi** [comment]
Controller buttons would work fine (just like you can still control the player with a controller while the console is open), but I doubt people will want to bind a controller button to close the debug console.

**Comment by DemoJameson** [comment]
> so it prevents you from using the load command to teleport to a room that contains ~ in its name

can't be loaded into a room with `~` just a minor issue, not worth changing people's habits over

my thought is to keep the hardcoded `~` button and its close function, the custom console button does not have a close function

**Comment by DemoJameson** [comment]
#685
