### ISSUE TITLE
Delayed Mod Loading

### ISSUE THREAD

**Issue by nQvTgLrp** [EverestAPI/Everest#708]
### I am planning on implementing this myself

No

### Describe your request

Can we delay mod loading to when it's actually used? Currently loading time is way too much at startup when having many mods.

**Comment by Kalobi** [comment]
The problem is that it's hard to determine when a mod is actually "used". Also e.g. texture loading while in a map will cause lag spikes. Some things that need a lot of memory are already lazy loaded (audio, endscreens), but more lazy loading is difficult to implement. (See e.g. the lazy loading implementation in CollabUtils2, which requires shipping a list of all textures used in each map.)

**Comment by Kalobi** [comment]
If your loading times are too long, you can disable mods that you're not currently playing.

**Comment by nQvTgLrp** [comment]
@Kalobi  What if we load the mods when entering a certain save? I think it's common that people use different saves for different maps. For example, I have a save specifically for SJC, when entering this one, it would be good to just load SJC when I start game and enter this save only.

**Comment by microlith57** [comment]
the trouble with that is that some mods affect things outside of saves; for instance adding stickers onto the save image, or adding settings to the settings menu, or any number of other things; and there's not really any way to tell if an asset will be used for that or not

**Comment by nQvTgLrp** [comment]
Fair point. Closing the issue since it's unclear how to implement this.
