### ISSUE TITLE
The 4465 release broke building stable releases on Linux

### ISSUE THREAD

**Issue by afontenot** [EverestAPI/Everest#718]
### My mods and Everest install are up to date

Yes

### I have recreated the bug with only Everest OR a minimum number of mods enabled

Yes

### Describe the bug

I've been building Everest releases from source code using the stable releases on Github. With 4465, this stopped working.

### Steps to reproduce

E.g.

1. `wget "https://github.com/EverestAPI/Everest/archive/refs/tags/stable-1.4465.0.tar.gz"`
2. `tar xf stable-1.4465.0.tar.gz`
3. `cd Everest-stable-1.4465.0`
4. `dotnet build --nologo --verbosity quiet "/p:Configuration=Release"`

I see a series of errors that look something like this:

/home/adam/downloads/everest/Everest-stable-1.4465.0/NETCoreifier/Coreifier.cs(3,7): error CS0246: The type or namespace name 'MonoMod' could not be found (are you missing a using directive or an assembly reference?) [/home/adam/downloads/everest/Everest-stable-1.4465.0/NETCoreifier/NETCoreifier.csproj]

All the errors I see (91 of them) are in the NetCoreifier project. At first I thought the issue had to do with missing submodules, but (a) this isn't an issue for previous stable releases, and (b) manually cloning monomod into the `external` directory doesn't fix the issue.

Incidentally, building the git version now fails as well unless I install the 6.0 version of the .NET framework. This isn't an issue for building the 4449 release - I have a working Celeste + Everest install on my system that I built with exclusively .NET 8.0 tooling.

### Expected behavior

The build succeeds. In fact, if you download the previous stable release (4449), the above series of commands works just fine.

### Operating System

Arch Linux

### Everest Version

4465

**Comment by afontenot** [comment]
I'm guessing this has to do with the switch to .NET Core. I'm not familiar enough with the internals to say exactly how this affects things, all I know is that `dotnet build` from the Arch Linux package for the .NET 8.0 SDK used to successfully build Everest, and now it doesn't.

**Comment by afontenot** [comment]
I figured out that the reason manually cloning the MonoMod repository doesn't work is that Everest depends specifically on commit [47cbea2](https://github.com/MonoMod/MonoMod/tree/47cbea2cee3ff7785d31599e8f9f0fbe38b5fecc). If you checkout this specific commit, then the build will work.

I'm not sure I understand why this is required when it wasn't needed previously, and also why .NET 6.0 is now required (to build MonoMod). I think at the very least the instructions for stable builds ought to be updated, since required dependencies currently have to be manually downloaded (as far as I can tell).

Edit: guessing the dotnet build tools automatically downloaded the legacy dotnet SDK (4.5.2) that was used to build previously, and now this doesn't happen, so you've got to manually install the SDK versions you need. Everest can be built with 7.0 but MonoMod requires 6.0 so unfortunately you need them both. Still not sure what's up with the submodule thing, maybe nuget was used for the MonoMod dependency previously?

**Comment by psyGamer** [comment]
The TAR you downloaded doesn't include submodules (blame GitHub for that), so you need to clone it recursivly with `git clone --recursive https://github.com/EverestAPI/Everest`.
Also you should use `dotnet publish` instead of `dotnet build`.
But is there a reason youre building them from source? Unless you plan on developping, consider using [Olympus](https://everestapi.github.io/#olympus) (GUI) or [mons](https://github.com/coloursofnoise/mons) (CLI) to install Everest.

**Comment by Kalobi** [comment]
> I think at the very least the instructions for stable builds ought to be updated, since required dependencies currently have to be manually downloaded (as far as I can tell).
 
The instructions have in fact been updated, both to tell you to clone submodules and to tell you to publish instead of build. Also as psyGamer said, there's no need to build Everest manually unless you want to contribute to development, you can install it via Olympus or mons or just by downloading and installing the GitHub release.

**Comment by Wartori54** [comment]
@afontenot was right in that MonoNod requires net6.0 to be build, together with net8.0, and this still applies to the latest commit from the `reorganize` branch.
Their suggestion to make clear that it is (currently) required net6.0 to build everest from source should be considered.
Finally, for anyone wondering what is the root cause of this, it boils down to `MonoMod.ILHelpers.Patcher`, a binary which can indeed be build with net8.0 but when ran it complains about not being able to find net6.0 exactly. This binary is ran by `MonoMod/tools/Common.IL.targets`.

**Comment by afontenot** [comment]
> But is there a reason youre building them from source? Unless you plan on developping, consider using [Olympus](https://everestapi.github.io/#olympus) (GUI) or [mons](https://github.com/coloursofnoise/mons) (CLI) to install Everest.

> there's no need to build Everest manually unless you want to contribute to development

This has been discussed previously in issues here, but neither does everything I need. I use [tools I've written myself](https://github.com/afontenot/grimper) instead. The README page for my project describes several features that are important to me.

> The instructions have in fact been updated, both to tell you to clone submodules

It's true that this is in the README, but it kinda sounded to me like this was for development, since it advises cloning the whole Everest repo. Anyone just building stable releases of most software would ordinarily just grab a source tarball, and it's a little annoying that you have to find precise versions of several dependencies *unless* you're starting with an Everest git repository (in which case you can indeed just clone the submodules recursively).

Edit: actually, the instructions say

> Clone the Everest repo + submodules, either in your IDE, via the CLI, or by downloading the .zip from GitHub.

This seems to imply that downloading the release ZIP file should include the submodules, but it doesn't! I think this should be corrected.

> Their suggestion to make clear that it is (currently) required net6.0 to build everest from source should be considered.

Thanks, I would indeed encourage clarifying this. :-)
