### ISSUE TITLE
(Linux) Use relative rather than absolute symlinks

### ISSUE THREAD

**Issue by micamoan** [EverestAPI/Everest#742]
### My mods and Everest install are up to date

Yes

### I have recreated the bug with only Everest OR a minimum number of mods enabled

Yes

### Describe the bug

Upon installing Everest in a clean Celeste folder, then moving the folder, the game no longer launches because of missing library files. This seems to be because the symlinked libraries use absolute rather than relative symlinks, so when you move the game folder those symlinks are broken. Changing these to relative symlinks resolves the issue:

```bash
cd ./lib64-linux
ln -sr --force libFAudio.so libFAudio.so.0
ln -sr --force libFNA3D.so libFNA3D.so.0
ln -sr --force libSDL2-2.0.so libSDL2-2.0.so.0
ln -sr --force libSDL2_image-2.0.so libSDL2_image-2.0.so.0
ln -sr --force libfmod.so libfmod.so.10
ln -sr --force libfmodstudio.so libfmodstudio.so.10
```

### Steps to reproduce

1. Install stable Everest
2. Move the game folder to a different location
3. Attempt to launch the game

### Expected behavior

The game should launch after the directory is moved.

### Operating System

Arch Linux

### Everest Version

4607

**Comment by Kalobi** [comment]
@micamoan Could you test the above PR on a fresh install? (MiniInstaller won't create new symlinks if they already exist, which is why the install has to be new.) You can download the [build artifact from Azure](https://dev.azure.com/EverestAPI/e877e744-b3c0-4e59-94d2-6042b8b565d2/_apis/build/builds/3949/artifacts?artifactName=main&api-version=7.1&%24format=zip) and install it using the [manual installation instructions on the Everest website](https://everestapi.github.io/#cross-platform-manual-installation).

**Comment by micamoan** [comment]
Works great, thanks.
