### ISSUE TITLE
The game crashed while disconnecting Bluetooth earphones on Windows

### ISSUE THREAD

**Issue by BEN425** [EverestAPI/Everest#778]
### My mods and Everest install are up to date

Yes

### I have recreated the bug with only Everest OR a minimum number of mods enabled

Yes

### Describe the bug

The game crashed when I disconnected my Bluetooth device on Windows.
It can happen without any mods.
I tried to reproduce it on vanilla Celeste, but the game didn't crash.

### Steps to reproduce

1. Connect a Bluetooth earphone to Windows.
2. Start Everest.
3. While the game is running, disconnect the Bluetooth device.

### Expected behavior

The game should not crash.

### Operating System

Windows 11

### Everest Version

v1.4818.0-azure

### Mods required to reproduce

None

### Additional context

**Video Demo:**
https://youtu.be/sHqqXvhcwGU

**Error log:**
```
Celeste Error Log
==========================================

Ver 1.4.0.0-fna [Everest: 4818-azure-8be6b]
06/18/2024 15:09:06
System.Exception: FMOD Failed: ERR_OUTPUT_INIT (Error initializing output device.)
   at Celeste.Audio.CheckFmod(RESULT result) in /home/vsts/work/1/s/Celeste.Mod.mm/Patches/Audio.cs:line 42
   at Celeste.Audio.Update()
   at Celeste.Celeste.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick() in /tmp/FNA/src/Game.cs:line 430
   at Microsoft.Xna.Framework.Game.RunLoop() in /tmp/FNA/src/Game.cs:line 875
   at Microsoft.Xna.Framework.Game.Run() in /tmp/FNA/src/Game.cs:line 416
   at Monocle.Engine.RunWithLogging() in /home/vsts/work/1/s/Celeste.Mod.mm/Patches/Monocle/Engine.cs:line 52
```

**Comment by SnipUndercover** [comment]
Something went wrong with the audio engine Celeste uses.
`ERR_OUTPUT_INIT` is a common error and has a number of fixes:
- Unplug/replug your speakers/headphones
- Try a different set of speakers/headphones
- Restart your audio drivers/your PC
- Update your audio drivers

This is not an issue in Everest, as it can also happen in vanilla. The problem lies in FMOD, which is  a third party library and is unaffiliated with Everest.
As such, we can't really do anything about it.
